service: movie-slackpy

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  endpointType: REGIONAL
  deploymentBucket:
    name: com.serverless.techfury.deploys
    serverSideEncryption: AES256

custom:
  customDomain:
    domainName: ${file(./config/${opt:stage, 'stage'}.yml):DOMAIN_NAME}
    basePath: moviepy
    stage: ${opt:stage, 'stage'}
    createRoute53Record: false
    endpointType: regional
  prune:
    automatic: true
    number: 3      
  pythonRequirements:
    dockerizePip: non-linux
  ssm: ${ssm:/aws/reference/secretsmanager/${opt:stage,'stage'}/moviepy-slack}

functions:
  main:
    name: ${sls:stage}-movie-slackpy
    handler: main.handler
    environment:
      BOT_NAME: "HAL 9000"
      EMOJI: ":hal_9000:"
      SLACK_WEBHOOK_URL: ${self:custom.ssm.SLACK_WEBHOOK_URL} 
      OMDB_API_KEY: ${self:custom.ssm.OMDB_API_KEY}
    events:
      - http:
          path: /
          method: POST
      - http:
          path: /{proxy+}
          method: POST

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!config/**'    

plugins:
  - serverless-domain-manager
  - serverless-prune-plugin
  - serverless-python-requirements
